/* SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause) */

/* THIS FILE IS AUTOGENERATED BY BPFTOOL! */
#ifndef __BPFTRACE_BPF_SKEL_H__
#define __BPFTRACE_BPF_SKEL_H__

#include <errno.h>
#include <stdlib.h>
#include <bpf/libbpf.h>

struct bpftrace_bpf {
	struct bpf_object_skeleton *skeleton;
	struct bpf_object *obj;
	struct {
		struct bpf_map *ustackmap;
		struct bpf_map *kstackmap;
		struct bpf_map *counts;
		struct bpf_map *rodata;
	} maps;
	struct {
		struct bpf_program *bpftrace;
	} progs;
	struct {
		struct bpf_link *bpftrace;
	} links;
	struct bpftrace_bpf__rodata {
		__u64 target_tgid;
	} *rodata;

#ifdef __cplusplus
	static inline struct bpftrace_bpf *open(const struct bpf_object_open_opts *opts = nullptr);
	static inline struct bpftrace_bpf *open_and_load();
	static inline int load(struct bpftrace_bpf *skel);
	static inline int attach(struct bpftrace_bpf *skel);
	static inline void detach(struct bpftrace_bpf *skel);
	static inline void destroy(struct bpftrace_bpf *skel);
	static inline const void *elf_bytes(size_t *sz);
#endif /* __cplusplus */
};

static void
bpftrace_bpf__destroy(struct bpftrace_bpf *obj)
{
	if (!obj)
		return;
	if (obj->skeleton)
		bpf_object__destroy_skeleton(obj->skeleton);
	free(obj);
}

static inline int
bpftrace_bpf__create_skeleton(struct bpftrace_bpf *obj);

static inline struct bpftrace_bpf *
bpftrace_bpf__open_opts(const struct bpf_object_open_opts *opts)
{
	struct bpftrace_bpf *obj;
	int err;

	obj = (struct bpftrace_bpf *)calloc(1, sizeof(*obj));
	if (!obj) {
		errno = ENOMEM;
		return NULL;
	}

	err = bpftrace_bpf__create_skeleton(obj);
	if (err)
		goto err_out;

	err = bpf_object__open_skeleton(obj->skeleton, opts);
	if (err)
		goto err_out;

	return obj;
err_out:
	bpftrace_bpf__destroy(obj);
	errno = -err;
	return NULL;
}

static inline struct bpftrace_bpf *
bpftrace_bpf__open(void)
{
	return bpftrace_bpf__open_opts(NULL);
}

static inline int
bpftrace_bpf__load(struct bpftrace_bpf *obj)
{
	return bpf_object__load_skeleton(obj->skeleton);
}

static inline struct bpftrace_bpf *
bpftrace_bpf__open_and_load(void)
{
	struct bpftrace_bpf *obj;
	int err;

	obj = bpftrace_bpf__open();
	if (!obj)
		return NULL;
	err = bpftrace_bpf__load(obj);
	if (err) {
		bpftrace_bpf__destroy(obj);
		errno = -err;
		return NULL;
	}
	return obj;
}

static inline int
bpftrace_bpf__attach(struct bpftrace_bpf *obj)
{
	return bpf_object__attach_skeleton(obj->skeleton);
}

static inline void
bpftrace_bpf__detach(struct bpftrace_bpf *obj)
{
	bpf_object__detach_skeleton(obj->skeleton);
}

static inline const void *bpftrace_bpf__elf_bytes(size_t *sz);

static inline int
bpftrace_bpf__create_skeleton(struct bpftrace_bpf *obj)
{
	struct bpf_object_skeleton *s;
	int err;

	s = (struct bpf_object_skeleton *)calloc(1, sizeof(*s));
	if (!s)	{
		err = -ENOMEM;
		goto err;
	}

	s->sz = sizeof(*s);
	s->name = "bpftrace_bpf";
	s->obj = &obj->obj;

	/* maps */
	s->map_cnt = 4;
	s->map_skel_sz = sizeof(*s->maps);
	s->maps = (struct bpf_map_skeleton *)calloc(s->map_cnt, s->map_skel_sz);
	if (!s->maps) {
		err = -ENOMEM;
		goto err;
	}

	s->maps[0].name = "ustackmap";
	s->maps[0].map = &obj->maps.ustackmap;

	s->maps[1].name = "kstackmap";
	s->maps[1].map = &obj->maps.kstackmap;

	s->maps[2].name = "counts";
	s->maps[2].map = &obj->maps.counts;

	s->maps[3].name = "bpftrace.rodata";
	s->maps[3].map = &obj->maps.rodata;
	s->maps[3].mmaped = (void **)&obj->rodata;

	/* programs */
	s->prog_cnt = 1;
	s->prog_skel_sz = sizeof(*s->progs);
	s->progs = (struct bpf_prog_skeleton *)calloc(s->prog_cnt, s->prog_skel_sz);
	if (!s->progs) {
		err = -ENOMEM;
		goto err;
	}

	s->progs[0].name = "bpftrace";
	s->progs[0].prog = &obj->progs.bpftrace;
	s->progs[0].link = &obj->links.bpftrace;

	s->data = bpftrace_bpf__elf_bytes(&s->data_sz);

	obj->skeleton = s;
	return 0;
err:
	bpf_object__destroy_skeleton(s);
	return err;
}

static inline const void *bpftrace_bpf__elf_bytes(size_t *sz)
{
	static const char data[] __attribute__((__aligned__(8))) = "\
\x7f\x45\x4c\x46\x02\x01\x01\0\0\0\0\0\0\0\0\0\x01\0\xf7\0\x01\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\x20\x10\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\x40\0\x0e\0\
\x01\0\xbf\x16\0\0\0\0\0\0\x85\0\0\0\x0e\0\0\0\x18\x01\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\x79\x12\0\0\0\0\0\0\x15\x02\x03\0\0\0\0\0\x79\x11\0\0\0\0\0\0\x77\0\0\0\
\x20\0\0\0\x5d\x10\x3b\0\0\0\0\0\xb7\x01\0\0\0\0\0\0\x7b\x1a\xf8\xff\0\0\0\0\
\xbf\x61\0\0\0\0\0\0\x18\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xb7\x03\0\0\0\x01\0\0\
\x85\0\0\0\x1b\0\0\0\x65\0\x05\0\xff\xff\xff\xff\x18\x01\0\0\xff\xff\xff\xff\0\
\0\0\0\0\0\0\0\x63\x1a\xf8\xff\0\0\0\0\xb7\x07\0\0\x01\0\0\0\x05\0\x09\0\0\0\0\
\0\xbf\x01\0\0\0\0\0\0\x67\x01\0\0\x20\0\0\0\x77\x01\0\0\x20\0\0\0\xb7\x07\0\0\
\x01\0\0\0\x18\x02\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\x1d\x21\x01\0\0\0\0\0\
\xb7\x07\0\0\0\0\0\0\x63\x0a\xf8\xff\0\0\0\0\xb7\x08\0\0\0\0\0\0\xbf\x61\0\0\0\
\0\0\0\x18\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xb7\x03\0\0\0\0\0\0\x85\0\0\0\x1b\0\
\0\0\xb7\x01\0\0\xff\xff\xff\xff\x6d\x08\x01\0\0\0\0\0\xbf\x01\0\0\0\0\0\0\x63\
\x1a\xfc\xff\0\0\0\0\x57\x07\0\0\x01\0\0\0\x15\x07\x05\0\0\0\0\0\x67\x01\0\0\
\x20\0\0\0\x77\x01\0\0\x20\0\0\0\x18\x02\0\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\
\x1d\x21\x14\0\0\0\0\0\xbf\xa2\0\0\0\0\0\0\x07\x02\0\0\xf8\xff\xff\xff\x18\x01\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x85\0\0\0\x01\0\0\0\x15\0\x04\0\0\0\0\0\x79\x01\0\
\0\0\0\0\0\x07\x01\0\0\x01\0\0\0\x7b\x10\0\0\0\0\0\0\x05\0\x0a\0\0\0\0\0\xb7\
\x01\0\0\x01\0\0\0\x7b\x1a\xf0\xff\0\0\0\0\xbf\xa2\0\0\0\0\0\0\x07\x02\0\0\xf8\
\xff\xff\xff\xbf\xa3\0\0\0\0\0\0\x07\x03\0\0\xf0\xff\xff\xff\x18\x01\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\xb7\x04\0\0\x01\0\0\0\x85\0\0\0\x02\0\0\0\xb7\0\0\0\0\0\0\0\
\x95\0\0\0\0\0\0\0\x44\x75\x61\x6c\x20\x42\x53\x44\x2f\x47\x50\x4c\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x9f\xeb\x01\0\x18\0\0\0\0\0\0\
\0\x3c\x03\0\0\x3c\x03\0\0\x94\x03\0\0\0\0\0\0\0\0\0\x02\x03\0\0\0\x01\0\0\0\0\
\0\0\x01\x04\0\0\0\x20\0\0\x01\0\0\0\0\0\0\0\x03\0\0\0\0\x02\0\0\0\x04\0\0\0\
\x07\0\0\0\x05\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\0\0\0\0\0\0\0\0\x02\x06\0\0\0\
\0\0\0\0\0\0\0\x03\0\0\0\0\x02\0\0\0\x04\0\0\0\0\x10\0\0\0\0\0\0\0\0\0\x02\x08\
\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\0\x02\0\0\0\x04\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\
\x02\x0a\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\0\x02\0\0\0\x04\0\0\0\xf8\x03\0\0\0\0\0\
\0\x04\0\0\x04\x20\0\0\0\x19\0\0\0\x01\0\0\0\0\0\0\0\x1e\0\0\0\x05\0\0\0\x40\0\
\0\0\x2a\0\0\0\x07\0\0\0\x80\0\0\0\x33\0\0\0\x09\0\0\0\xc0\0\0\0\x3e\0\0\0\0\0\
\0\x0e\x0b\0\0\0\x01\0\0\0\0\0\0\0\x04\0\0\x04\x20\0\0\0\x19\0\0\0\x01\0\0\0\0\
\0\0\0\x1e\0\0\0\x05\0\0\0\x40\0\0\0\x2a\0\0\0\x07\0\0\0\x80\0\0\0\x33\0\0\0\
\x09\0\0\0\xc0\0\0\0\x48\0\0\0\0\0\0\x0e\x0d\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\x02\
\x10\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\0\x02\0\0\0\x04\0\0\0\x01\0\0\0\0\0\0\0\0\0\
\0\x02\x12\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\0\x02\0\0\0\x04\0\0\0\0\x40\0\0\0\0\0\
\0\0\0\0\x02\x14\0\0\0\x52\0\0\0\x02\0\0\x04\x08\0\0\0\x58\0\0\0\x15\0\0\0\0\0\
\0\0\x61\0\0\0\x15\0\0\0\x20\0\0\0\x6a\0\0\0\0\0\0\x08\x16\0\0\0\x70\0\0\0\0\0\
\0\x01\x04\0\0\0\x20\0\0\0\0\0\0\0\0\0\0\x02\x18\0\0\0\x7d\0\0\0\0\0\0\x08\x19\
\0\0\0\x83\0\0\0\0\0\0\x01\x08\0\0\0\x40\0\0\0\0\0\0\0\x04\0\0\x04\x20\0\0\0\
\x19\0\0\0\x0f\0\0\0\0\0\0\0\x1e\0\0\0\x11\0\0\0\x40\0\0\0\x96\0\0\0\x13\0\0\0\
\x80\0\0\0\x9a\0\0\0\x17\0\0\0\xc0\0\0\0\xa0\0\0\0\0\0\0\x0e\x1a\0\0\0\x01\0\0\
\0\0\0\0\0\0\0\0\x02\0\0\0\0\0\0\0\0\x01\0\0\x0d\x02\0\0\0\xa7\0\0\0\x1c\0\0\0\
\xab\0\0\0\x01\0\0\x0c\x1d\0\0\0\x65\x03\0\0\0\0\0\x01\x01\0\0\0\x08\0\0\x01\0\
\0\0\0\0\0\0\x03\0\0\0\0\x1f\0\0\0\x04\0\0\0\x0d\0\0\0\x6a\x03\0\0\0\0\0\x0e\
\x20\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\x0a\x23\0\0\0\0\0\0\0\0\0\0\x09\x18\0\0\0\
\x72\x03\0\0\0\0\0\x0e\x22\0\0\0\x01\0\0\0\x7e\x03\0\0\x03\0\0\x0f\0\0\0\0\x0c\
\0\0\0\0\0\0\0\x20\0\0\0\x0e\0\0\0\0\0\0\0\x20\0\0\0\x1b\0\0\0\0\0\0\0\x20\0\0\
\0\x84\x03\0\0\x01\0\0\x0f\0\0\0\0\x24\0\0\0\0\0\0\0\x08\0\0\0\x8c\x03\0\0\x01\
\0\0\x0f\0\0\0\0\x21\0\0\0\0\0\0\0\x0d\0\0\0\0\x69\x6e\x74\0\x5f\x5f\x41\x52\
\x52\x41\x59\x5f\x53\x49\x5a\x45\x5f\x54\x59\x50\x45\x5f\x5f\0\x74\x79\x70\x65\
\0\x6d\x61\x78\x5f\x65\x6e\x74\x72\x69\x65\x73\0\x6b\x65\x79\x5f\x73\x69\x7a\
\x65\0\x76\x61\x6c\x75\x65\x5f\x73\x69\x7a\x65\0\x75\x73\x74\x61\x63\x6b\x6d\
\x61\x70\0\x6b\x73\x74\x61\x63\x6b\x6d\x61\x70\0\x6b\x65\x79\x5f\x74\0\x75\x73\
\x74\x61\x63\x6b\x69\x64\0\x6b\x73\x74\x61\x63\x6b\x69\x64\0\x5f\x5f\x75\x33\
\x32\0\x75\x6e\x73\x69\x67\x6e\x65\x64\x20\x69\x6e\x74\0\x5f\x5f\x75\x36\x34\0\
\x75\x6e\x73\x69\x67\x6e\x65\x64\x20\x6c\x6f\x6e\x67\x20\x6c\x6f\x6e\x67\0\x6b\
\x65\x79\0\x76\x61\x6c\x75\x65\0\x63\x6f\x75\x6e\x74\x73\0\x63\x74\x78\0\x62\
\x70\x66\x74\x72\x61\x63\x65\0\x70\x65\x72\x66\x5f\x65\x76\x65\x6e\x74\0\x2f\
\x68\x6f\x6d\x65\x2f\x6a\x69\x6e\x2f\x61\x72\x6d\x36\x34\x5f\x6c\x69\x62\x2f\
\x62\x70\x66\x2d\x65\x78\x61\x6d\x70\x6c\x65\x2f\x62\x70\x66\x74\x72\x61\x63\
\x65\x2f\x62\x70\x66\x74\x72\x61\x63\x65\x2e\x62\x70\x66\x2e\x63\0\x69\x6e\x74\
\x20\x62\x70\x66\x74\x72\x61\x63\x65\x28\x76\x6f\x69\x64\x20\x2a\x63\x74\x78\
\x29\0\x20\x20\x20\x20\x5f\x5f\x75\x36\x34\x20\x74\x67\x69\x64\x20\x3d\x20\x62\
\x70\x66\x5f\x67\x65\x74\x5f\x63\x75\x72\x72\x65\x6e\x74\x5f\x70\x69\x64\x5f\
\x74\x67\x69\x64\x28\x29\x20\x3e\x3e\x20\x33\x32\x3b\0\x20\x20\x20\x20\x69\x66\
\x20\x28\x74\x61\x72\x67\x65\x74\x5f\x74\x67\x69\x64\x20\x21\x3d\x20\x30\x20\
\x26\x26\x20\x74\x67\x69\x64\x20\x21\x3d\x20\x74\x61\x72\x67\x65\x74\x5f\x74\
\x67\x69\x64\x29\0\x20\x20\x20\x20\x73\x74\x72\x75\x63\x74\x20\x6b\x65\x79\x5f\
\x74\x20\x6b\x65\x79\x20\x3d\x20\x7b\x7d\x3b\0\x20\x20\x20\x20\x73\x69\x64\x20\
\x3d\x20\x62\x70\x66\x5f\x67\x65\x74\x5f\x73\x74\x61\x63\x6b\x69\x64\x28\x63\
\x74\x78\x2c\x20\x26\x75\x73\x74\x61\x63\x6b\x6d\x61\x70\x2c\x20\x42\x50\x46\
\x5f\x46\x5f\x55\x53\x45\x52\x5f\x53\x54\x41\x43\x4b\x29\x3b\0\x20\x20\x20\x20\
\x69\x66\x20\x28\x73\x69\x64\x20\x3c\x20\x30\x29\0\x20\x20\x20\x20\x20\x20\x20\
\x20\x6b\x65\x79\x2e\x75\x73\x74\x61\x63\x6b\x69\x64\x20\x3d\x20\x28\x5f\x5f\
\x75\x33\x32\x29\x2d\x31\x3b\0\x20\x20\x20\x20\x20\x20\x20\x20\x6b\x65\x79\x2e\
\x75\x73\x74\x61\x63\x6b\x69\x64\x20\x3d\x20\x28\x5f\x5f\x75\x33\x32\x29\x73\
\x69\x64\x3b\0\x20\x20\x20\x20\x73\x69\x64\x20\x3d\x20\x62\x70\x66\x5f\x67\x65\
\x74\x5f\x73\x74\x61\x63\x6b\x69\x64\x28\x63\x74\x78\x2c\x20\x26\x6b\x73\x74\
\x61\x63\x6b\x6d\x61\x70\x2c\x20\x30\x29\x3b\0\x20\x20\x20\x20\x20\x20\x20\x20\
\x6b\x65\x79\x2e\x6b\x73\x74\x61\x63\x6b\x69\x64\x20\x3d\x20\x28\x5f\x5f\x75\
\x33\x32\x29\x2d\x31\x3b\0\x20\x20\x20\x20\x69\x66\x20\x28\x6b\x65\x79\x2e\x75\
\x73\x74\x61\x63\x6b\x69\x64\x20\x3d\x3d\x20\x28\x5f\x5f\x75\x33\x32\x29\x2d\
\x31\x20\x26\x26\x20\x6b\x65\x79\x2e\x6b\x73\x74\x61\x63\x6b\x69\x64\x20\x3d\
\x3d\x20\x28\x5f\x5f\x75\x33\x32\x29\x2d\x31\x29\0\x20\x20\x20\x20\x5f\x5f\x75\
\x36\x34\x20\x2a\x63\x6f\x75\x6e\x74\x20\x3d\x20\x62\x70\x66\x5f\x6d\x61\x70\
\x5f\x6c\x6f\x6f\x6b\x75\x70\x5f\x65\x6c\x65\x6d\x28\x26\x63\x6f\x75\x6e\x74\
\x73\x2c\x20\x26\x6b\x65\x79\x29\x3b\0\x20\x20\x20\x20\x69\x66\x20\x28\x63\x6f\
\x75\x6e\x74\x29\0\x20\x20\x20\x20\x20\x20\x20\x20\x28\x2a\x63\x6f\x75\x6e\x74\
\x29\x2b\x2b\x3b\0\x20\x20\x20\x20\x20\x20\x20\x20\x5f\x5f\x75\x36\x34\x20\x6f\
\x6e\x65\x20\x3d\x20\x31\x3b\0\x20\x20\x20\x20\x20\x20\x20\x20\x62\x70\x66\x5f\
\x6d\x61\x70\x5f\x75\x70\x64\x61\x74\x65\x5f\x65\x6c\x65\x6d\x28\x26\x63\x6f\
\x75\x6e\x74\x73\x2c\x20\x26\x6b\x65\x79\x2c\x20\x26\x6f\x6e\x65\x2c\x20\x42\
\x50\x46\x5f\x4e\x4f\x45\x58\x49\x53\x54\x29\x3b\0\x7d\0\x63\x68\x61\x72\0\x4c\
\x49\x43\x45\x4e\x53\x45\0\x74\x61\x72\x67\x65\x74\x5f\x74\x67\x69\x64\0\x2e\
\x6d\x61\x70\x73\0\x2e\x72\x6f\x64\x61\x74\x61\0\x6c\x69\x63\x65\x6e\x73\x65\0\
\x9f\xeb\x01\0\x20\0\0\0\0\0\0\0\x14\0\0\0\x14\0\0\0\x8c\x01\0\0\xa0\x01\0\0\0\
\0\0\0\x08\0\0\0\xb4\0\0\0\x01\0\0\0\0\0\0\0\x1e\0\0\0\x10\0\0\0\xb4\0\0\0\x18\
\0\0\0\0\0\0\0\xbf\0\0\0\xf7\0\0\0\0\x8c\0\0\x08\0\0\0\xbf\0\0\0\x0f\x01\0\0\
\x12\x94\0\0\x10\0\0\0\xbf\0\0\0\x42\x01\0\0\x09\x98\0\0\x28\0\0\0\xbf\0\0\0\
\x42\x01\0\0\x1a\x98\0\0\x30\0\0\0\xbf\0\0\0\x42\x01\0\0\x25\x98\0\0\x38\0\0\0\
\xbf\0\0\0\x0f\x01\0\0\x2d\x94\0\0\x40\0\0\0\xbf\0\0\0\x42\x01\0\0\x09\x98\0\0\
\x50\0\0\0\xbf\0\0\0\x73\x01\0\0\x12\xa4\0\0\x58\0\0\0\xbf\0\0\0\x8e\x01\0\0\
\x0b\xb0\0\0\x80\0\0\0\xbf\0\0\0\xcc\x01\0\0\x09\xb4\0\0\x98\0\0\0\xbf\0\0\0\
\xdd\x01\0\0\x16\xb8\0\0\xb0\0\0\0\xbf\0\0\0\xff\x01\0\0\x18\xc0\0\0\xf0\0\0\0\
\xbf\0\0\0\xff\x01\0\0\x16\xc0\0\0\0\x01\0\0\xbf\0\0\0\x22\x02\0\0\x0b\xc8\0\0\
\x30\x01\0\0\xbf\0\0\0\xcc\x01\0\0\x09\xcc\0\0\x40\x01\0\0\xbf\0\0\0\x51\x02\0\
\0\x16\xd0\0\0\x48\x01\0\0\xbf\0\0\0\x73\x02\0\0\x23\xe0\0\0\x88\x01\0\0\xbf\0\
\0\0\xb3\x02\0\0\x14\xec\0\0\xa8\x01\0\0\xbf\0\0\0\xea\x02\0\0\x09\xf0\0\0\xb0\
\x01\0\0\xbf\0\0\0\xf9\x02\0\0\x11\xf4\0\0\xd8\x01\0\0\xbf\0\0\0\x0d\x03\0\0\
\x0f\0\x01\0\xe8\x01\0\0\xbf\0\0\0\0\0\0\0\0\0\0\0\0\x02\0\0\xbf\0\0\0\x24\x03\
\0\0\x09\x04\x01\0\x20\x02\0\0\xbf\0\0\0\x63\x03\0\0\x01\x14\x01\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\xc4\0\0\0\0\0\x03\0\x48\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xb4\0\0\0\0\0\
\x03\0\x20\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xad\0\0\0\0\0\x03\0\xb0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\x9f\0\0\0\0\0\x03\0\xf8\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xa6\0\
\0\0\0\0\x03\0\xf0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x98\0\0\0\0\0\x03\0\x40\x01\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\xcb\0\0\0\0\0\x03\0\x80\x01\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\xbc\0\0\0\0\0\x03\0\xd0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x5a\0\0\0\x12\0\
\x03\0\0\0\0\0\0\0\0\0\x30\x02\0\0\0\0\0\0\x63\0\0\0\x11\0\x06\0\0\0\0\0\0\0\0\
\0\x08\0\0\0\0\0\0\0\x30\0\0\0\x11\0\x07\0\0\0\0\0\0\0\0\0\x20\0\0\0\0\0\0\0\
\x3a\0\0\0\x11\0\x07\0\x20\0\0\0\0\0\0\0\x20\0\0\0\0\0\0\0\x23\0\0\0\x11\0\x07\
\0\x40\0\0\0\0\0\0\0\x20\0\0\0\0\0\0\0\x90\0\0\0\x11\0\x05\0\0\0\0\0\0\0\0\0\
\x0d\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x01\0\0\0\x0b\0\0\0\x60\0\0\0\0\0\0\0\x01\
\0\0\0\x0c\0\0\0\x08\x01\0\0\0\0\0\0\x01\0\0\0\x0d\0\0\0\x90\x01\0\0\0\0\0\0\
\x01\0\0\0\x0e\0\0\0\0\x02\0\0\0\0\0\0\x01\0\0\0\x0e\0\0\0\x04\x03\0\0\0\0\0\0\
\x04\0\0\0\x0c\0\0\0\x10\x03\0\0\0\0\0\0\x04\0\0\0\x0d\0\0\0\x1c\x03\0\0\0\0\0\
\0\x04\0\0\0\x0e\0\0\0\x34\x03\0\0\0\0\0\0\x03\0\0\0\x0b\0\0\0\x4c\x03\0\0\0\0\
\0\0\x04\0\0\0\x0f\0\0\0\x2c\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x40\0\0\0\0\0\0\
\0\x04\0\0\0\x01\0\0\0\x50\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x60\0\0\0\0\0\0\0\
\x04\0\0\0\x01\0\0\0\x70\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x80\0\0\0\0\0\0\0\
\x04\0\0\0\x01\0\0\0\x90\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\xa0\0\0\0\0\0\0\0\
\x04\0\0\0\x01\0\0\0\xb0\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\xc0\0\0\0\0\0\0\0\
\x04\0\0\0\x01\0\0\0\xd0\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\xe0\0\0\0\0\0\0\0\
\x04\0\0\0\x01\0\0\0\xf0\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\0\x01\0\0\0\0\0\0\
\x04\0\0\0\x01\0\0\0\x10\x01\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x20\x01\0\0\0\0\0\
\0\x04\0\0\0\x01\0\0\0\x30\x01\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x40\x01\0\0\0\0\
\0\0\x04\0\0\0\x01\0\0\0\x50\x01\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x60\x01\0\0\0\
\0\0\0\x04\0\0\0\x01\0\0\0\x70\x01\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x80\x01\0\0\
\0\0\0\0\x04\0\0\0\x01\0\0\0\x90\x01\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\xa0\x01\0\
\0\0\0\0\0\x04\0\0\0\x01\0\0\0\xb0\x01\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x13\x18\
\x14\x15\x16\x17\0\x2e\x74\x65\x78\x74\0\x2e\x72\x65\x6c\x2e\x42\x54\x46\x2e\
\x65\x78\x74\0\x2e\x72\x65\x6c\x70\x65\x72\x66\x5f\x65\x76\x65\x6e\x74\0\x63\
\x6f\x75\x6e\x74\x73\0\x2e\x6d\x61\x70\x73\0\x75\x73\x74\x61\x63\x6b\x6d\x61\
\x70\0\x6b\x73\x74\x61\x63\x6b\x6d\x61\x70\0\x2e\x6c\x6c\x76\x6d\x5f\x61\x64\
\x64\x72\x73\x69\x67\0\x6c\x69\x63\x65\x6e\x73\x65\0\x62\x70\x66\x74\x72\x61\
\x63\x65\0\x74\x61\x72\x67\x65\x74\x5f\x74\x67\x69\x64\0\x2e\x73\x74\x72\x74\
\x61\x62\0\x2e\x73\x79\x6d\x74\x61\x62\0\x2e\x72\x6f\x64\x61\x74\x61\0\x2e\x72\
\x65\x6c\x2e\x42\x54\x46\0\x4c\x49\x43\x45\x4e\x53\x45\0\x4c\x42\x42\x30\x5f\
\x39\0\x4c\x42\x42\x30\x5f\x37\0\x4c\x42\x42\x30\x5f\x36\0\x4c\x42\x42\x30\x5f\
\x34\0\x4c\x42\x42\x30\x5f\x31\x34\0\x4c\x42\x42\x30\x5f\x31\x33\0\x4c\x42\x42\
\x30\x5f\x32\0\x4c\x42\x42\x30\x5f\x31\x31\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x6f\0\0\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\x46\x0f\0\0\0\0\0\0\xd3\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\x01\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x18\
\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\x30\x02\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x14\0\0\0\x09\0\0\
\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x10\x0d\0\0\0\0\0\0\x50\0\0\0\0\0\0\0\x0d\
\0\0\0\x03\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x52\0\0\0\x01\0\0\0\x03\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x70\x02\0\0\0\0\0\0\x0d\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x7f\0\0\0\x01\0\0\0\x02\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\x80\x02\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\x2a\0\0\0\x01\0\0\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x88\x02\0\0\0\0\0\0\x60\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\x8b\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xe8\x02\0\0\0\0\
\0\0\xe8\x06\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x87\
\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x60\x0d\0\0\0\0\0\0\x50\0\0\
\0\0\0\0\0\x0d\0\0\0\x08\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x0b\0\0\0\
\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xd0\x09\0\0\0\0\0\0\xc0\x01\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x07\0\0\0\x09\0\0\0\x40\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xb0\x0d\0\0\0\0\0\0\x90\x01\0\0\0\0\0\0\x0d\0\0\
\0\x0a\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x44\0\0\0\x03\x4c\xff\x6f\0\0\
\0\x80\0\0\0\0\0\0\0\0\0\0\0\0\x40\x0f\0\0\0\0\0\0\x06\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x77\0\0\0\x02\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\x90\x0b\0\0\0\0\0\0\x80\x01\0\0\0\0\0\0\x01\0\0\0\x0a\0\0\0\x08\
\0\0\0\0\0\0\0\x18\0\0\0\0\0\0\0";

	*sz = sizeof(data) - 1;
	return (const void *)data;
}

#ifdef __cplusplus
struct bpftrace_bpf *bpftrace_bpf::open(const struct bpf_object_open_opts *opts) { return bpftrace_bpf__open_opts(opts); }
struct bpftrace_bpf *bpftrace_bpf::open_and_load() { return bpftrace_bpf__open_and_load(); }
int bpftrace_bpf::load(struct bpftrace_bpf *skel) { return bpftrace_bpf__load(skel); }
int bpftrace_bpf::attach(struct bpftrace_bpf *skel) { return bpftrace_bpf__attach(skel); }
void bpftrace_bpf::detach(struct bpftrace_bpf *skel) { bpftrace_bpf__detach(skel); }
void bpftrace_bpf::destroy(struct bpftrace_bpf *skel) { bpftrace_bpf__destroy(skel); }
const void *bpftrace_bpf::elf_bytes(size_t *sz) { return bpftrace_bpf__elf_bytes(sz); }
#endif /* __cplusplus */

__attribute__((unused)) static void
bpftrace_bpf__assert(struct bpftrace_bpf *s __attribute__((unused)))
{
#ifdef __cplusplus
#define _Static_assert static_assert
#endif
	_Static_assert(sizeof(s->rodata->target_tgid) == 8, "unexpected size of 'target_tgid'");
#ifdef __cplusplus
#undef _Static_assert
#endif
}

#endif /* __BPFTRACE_BPF_SKEL_H__ */
