/* SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause) */

/* THIS FILE IS AUTOGENERATED BY BPFTOOL! */
#ifndef __XDP_BPF_SKEL_H__
#define __XDP_BPF_SKEL_H__

#include <errno.h>
#include <stdlib.h>
#include <bpf/libbpf.h>

struct xdp_bpf {
	struct bpf_object_skeleton *skeleton;
	struct bpf_object *obj;
	struct {
		struct bpf_map *rodata;
	} maps;
	struct {
		struct bpf_program *xdp_pass;
	} progs;
	struct {
		struct bpf_link *xdp_pass;
	} links;

#ifdef __cplusplus
	static inline struct xdp_bpf *open(const struct bpf_object_open_opts *opts = nullptr);
	static inline struct xdp_bpf *open_and_load();
	static inline int load(struct xdp_bpf *skel);
	static inline int attach(struct xdp_bpf *skel);
	static inline void detach(struct xdp_bpf *skel);
	static inline void destroy(struct xdp_bpf *skel);
	static inline const void *elf_bytes(size_t *sz);
#endif /* __cplusplus */
};

static void
xdp_bpf__destroy(struct xdp_bpf *obj)
{
	if (!obj)
		return;
	if (obj->skeleton)
		bpf_object__destroy_skeleton(obj->skeleton);
	free(obj);
}

static inline int
xdp_bpf__create_skeleton(struct xdp_bpf *obj);

static inline struct xdp_bpf *
xdp_bpf__open_opts(const struct bpf_object_open_opts *opts)
{
	struct xdp_bpf *obj;
	int err;

	obj = (struct xdp_bpf *)calloc(1, sizeof(*obj));
	if (!obj) {
		errno = ENOMEM;
		return NULL;
	}

	err = xdp_bpf__create_skeleton(obj);
	if (err)
		goto err_out;

	err = bpf_object__open_skeleton(obj->skeleton, opts);
	if (err)
		goto err_out;

	return obj;
err_out:
	xdp_bpf__destroy(obj);
	errno = -err;
	return NULL;
}

static inline struct xdp_bpf *
xdp_bpf__open(void)
{
	return xdp_bpf__open_opts(NULL);
}

static inline int
xdp_bpf__load(struct xdp_bpf *obj)
{
	return bpf_object__load_skeleton(obj->skeleton);
}

static inline struct xdp_bpf *
xdp_bpf__open_and_load(void)
{
	struct xdp_bpf *obj;
	int err;

	obj = xdp_bpf__open();
	if (!obj)
		return NULL;
	err = xdp_bpf__load(obj);
	if (err) {
		xdp_bpf__destroy(obj);
		errno = -err;
		return NULL;
	}
	return obj;
}

static inline int
xdp_bpf__attach(struct xdp_bpf *obj)
{
	return bpf_object__attach_skeleton(obj->skeleton);
}

static inline void
xdp_bpf__detach(struct xdp_bpf *obj)
{
	bpf_object__detach_skeleton(obj->skeleton);
}

static inline const void *xdp_bpf__elf_bytes(size_t *sz);

static inline int
xdp_bpf__create_skeleton(struct xdp_bpf *obj)
{
	struct bpf_object_skeleton *s;
	int err;

	s = (struct bpf_object_skeleton *)calloc(1, sizeof(*s));
	if (!s)	{
		err = -ENOMEM;
		goto err;
	}

	s->sz = sizeof(*s);
	s->name = "xdp_bpf";
	s->obj = &obj->obj;

	/* maps */
	s->map_cnt = 1;
	s->map_skel_sz = sizeof(*s->maps);
	s->maps = (struct bpf_map_skeleton *)calloc(s->map_cnt, s->map_skel_sz);
	if (!s->maps) {
		err = -ENOMEM;
		goto err;
	}

	s->maps[0].name = "xdp_bpf.rodata";
	s->maps[0].map = &obj->maps.rodata;

	/* programs */
	s->prog_cnt = 1;
	s->prog_skel_sz = sizeof(*s->progs);
	s->progs = (struct bpf_prog_skeleton *)calloc(s->prog_cnt, s->prog_skel_sz);
	if (!s->progs) {
		err = -ENOMEM;
		goto err;
	}

	s->progs[0].name = "xdp_pass";
	s->progs[0].prog = &obj->progs.xdp_pass;
	s->progs[0].link = &obj->links.xdp_pass;

	s->data = xdp_bpf__elf_bytes(&s->data_sz);

	obj->skeleton = s;
	return 0;
err:
	bpf_object__destroy_skeleton(s);
	return err;
}

static inline const void *xdp_bpf__elf_bytes(size_t *sz)
{
	static const char data[] __attribute__((__aligned__(8))) = "\
\x7f\x45\x4c\x46\x02\x01\x01\0\0\0\0\0\0\0\0\0\x01\0\xf7\0\x01\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\x38\x06\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\x40\0\x0d\0\
\x01\0\x61\x12\0\0\0\0\0\0\x61\x13\x04\0\0\0\0\0\x1f\x23\0\0\0\0\0\0\x18\x01\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\xb7\x02\0\0\x12\0\0\0\x85\0\0\0\x06\0\0\0\xb7\0\0\0\
\x02\0\0\0\x95\0\0\0\0\0\0\0\x70\x61\x63\x6b\x65\x74\x20\x73\x69\x7a\x65\x20\
\x69\x73\x20\x25\x64\0\x47\x50\x4c\0\0\0\x9f\xeb\x01\0\x18\0\0\0\0\0\0\0\x58\
\x01\0\0\x58\x01\0\0\xae\x01\0\0\0\0\0\0\0\0\0\x02\x02\0\0\0\x01\0\0\0\x06\0\0\
\x04\x18\0\0\0\x08\0\0\0\x03\0\0\0\0\0\0\0\x0d\0\0\0\x03\0\0\0\x20\0\0\0\x16\0\
\0\0\x03\0\0\0\x40\0\0\0\x20\0\0\0\x03\0\0\0\x60\0\0\0\x30\0\0\0\x03\0\0\0\x80\
\0\0\0\x3f\0\0\0\x03\0\0\0\xa0\0\0\0\x4e\0\0\0\0\0\0\x08\x04\0\0\0\x54\0\0\0\0\
\0\0\x01\x04\0\0\0\x20\0\0\0\0\0\0\0\x01\0\0\x0d\x06\0\0\0\x61\0\0\0\x01\0\0\0\
\x65\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\x01\x69\0\0\0\x01\0\0\x0c\x05\0\0\0\0\0\
\0\0\0\0\0\x0a\x09\0\0\0\x6a\x01\0\0\0\0\0\x01\x01\0\0\0\x08\0\0\x01\0\0\0\0\0\
\0\0\x03\0\0\0\0\x08\0\0\0\x0b\0\0\0\x12\0\0\0\x6f\x01\0\0\0\0\0\x01\x04\0\0\0\
\x20\0\0\0\x83\x01\0\0\0\0\0\x0e\x0a\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\0\
\x09\0\0\0\x0b\0\0\0\x04\0\0\0\x94\x01\0\0\0\0\0\x0e\x0d\0\0\0\x01\0\0\0\x9e\
\x01\0\0\x01\0\0\x0f\0\0\0\0\x0c\0\0\0\0\0\0\0\x12\0\0\0\xa6\x01\0\0\x01\0\0\
\x0f\0\0\0\0\x0e\0\0\0\0\0\0\0\x04\0\0\0\0\x78\x64\x70\x5f\x6d\x64\0\x64\x61\
\x74\x61\0\x64\x61\x74\x61\x5f\x65\x6e\x64\0\x64\x61\x74\x61\x5f\x6d\x65\x74\
\x61\0\x69\x6e\x67\x72\x65\x73\x73\x5f\x69\x66\x69\x6e\x64\x65\x78\0\x72\x78\
\x5f\x71\x75\x65\x75\x65\x5f\x69\x6e\x64\x65\x78\0\x65\x67\x72\x65\x73\x73\x5f\
\x69\x66\x69\x6e\x64\x65\x78\0\x5f\x5f\x75\x33\x32\0\x75\x6e\x73\x69\x67\x6e\
\x65\x64\x20\x69\x6e\x74\0\x63\x74\x78\0\x69\x6e\x74\0\x78\x64\x70\x5f\x70\x61\
\x73\x73\0\x78\x64\x70\0\x30\x3a\x30\0\x2f\x68\x6f\x6d\x65\x2f\x6a\x69\x6e\x2f\
\x61\x72\x6d\x36\x34\x5f\x6c\x69\x62\x2f\x62\x70\x66\x2d\x65\x78\x61\x6d\x70\
\x6c\x65\x2f\x78\x64\x70\x2f\x78\x64\x70\x2e\x62\x70\x66\x2e\x63\0\x20\x20\x20\
\x20\x76\x6f\x69\x64\x2a\x20\x64\x61\x74\x61\x20\x3d\x20\x28\x76\x6f\x69\x64\
\x2a\x29\x28\x6c\x6f\x6e\x67\x29\x63\x74\x78\x2d\x3e\x64\x61\x74\x61\x3b\0\x30\
\x3a\x31\0\x20\x20\x20\x20\x76\x6f\x69\x64\x2a\x20\x64\x61\x74\x61\x5f\x65\x6e\
\x64\x20\x3d\x20\x28\x76\x6f\x69\x64\x2a\x29\x28\x6c\x6f\x6e\x67\x29\x63\x74\
\x78\x2d\x3e\x64\x61\x74\x61\x5f\x65\x6e\x64\x3b\0\x20\x20\x20\x20\x69\x6e\x74\
\x20\x70\x6b\x74\x5f\x73\x7a\x20\x3d\x20\x64\x61\x74\x61\x5f\x65\x6e\x64\x20\
\x2d\x20\x64\x61\x74\x61\x3b\0\x20\x20\x20\x20\x62\x70\x66\x5f\x70\x72\x69\x6e\
\x74\x6b\x28\x22\x70\x61\x63\x6b\x65\x74\x20\x73\x69\x7a\x65\x20\x69\x73\x20\
\x25\x64\x22\x2c\x20\x70\x6b\x74\x5f\x73\x7a\x29\x3b\0\x20\x20\x20\x20\x72\x65\
\x74\x75\x72\x6e\x20\x58\x44\x50\x5f\x50\x41\x53\x53\x3b\0\x63\x68\x61\x72\0\
\x5f\x5f\x41\x52\x52\x41\x59\x5f\x53\x49\x5a\x45\x5f\x54\x59\x50\x45\x5f\x5f\0\
\x78\x64\x70\x5f\x70\x61\x73\x73\x2e\x5f\x5f\x5f\x5f\x66\x6d\x74\0\x5f\x5f\x6c\
\x69\x63\x65\x6e\x73\x65\0\x2e\x72\x6f\x64\x61\x74\x61\0\x6c\x69\x63\x65\x6e\
\x73\x65\0\0\0\x9f\xeb\x01\0\x20\0\0\0\0\0\0\0\x14\0\0\0\x14\0\0\0\x5c\0\0\0\
\x70\0\0\0\x2c\0\0\0\x08\0\0\0\x72\0\0\0\x01\0\0\0\0\0\0\0\x07\0\0\0\x10\0\0\0\
\x72\0\0\0\x05\0\0\0\0\0\0\0\x7a\0\0\0\xa8\0\0\0\x24\x24\0\0\x08\0\0\0\x7a\0\0\
\0\xd5\0\0\0\x28\x28\0\0\x10\0\0\0\x7a\0\0\0\x06\x01\0\0\x1b\x2c\0\0\x18\0\0\0\
\x7a\0\0\0\x28\x01\0\0\x05\x34\0\0\x38\0\0\0\x7a\0\0\0\x55\x01\0\0\x05\x38\0\0\
\x10\0\0\0\x72\0\0\0\x02\0\0\0\0\0\0\0\x02\0\0\0\x76\0\0\0\0\0\0\0\x08\0\0\0\
\x02\0\0\0\xd1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\x03\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x14\0\0\0\x01\0\x05\
\0\0\0\0\0\0\0\0\0\x12\0\0\0\0\0\0\0\0\0\0\0\x03\0\x05\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\x25\0\0\0\x12\0\x03\0\0\0\0\0\0\0\0\0\x48\0\0\0\0\0\0\0\x44\0\0\0\
\x11\0\x06\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\x18\0\0\0\0\0\0\0\x01\0\0\0\x03\
\0\0\0\x50\x01\0\0\0\0\0\0\x03\0\0\0\x03\0\0\0\x68\x01\0\0\0\0\0\0\x04\0\0\0\
\x05\0\0\0\x2c\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x40\0\0\0\0\0\0\0\x04\0\0\0\
\x01\0\0\0\x50\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x60\0\0\0\0\0\0\0\x04\0\0\0\
\x01\0\0\0\x70\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\x80\0\0\0\0\0\0\0\x04\0\0\0\
\x01\0\0\0\x9c\0\0\0\0\0\0\0\x04\0\0\0\x01\0\0\0\xac\0\0\0\0\0\0\0\x04\0\0\0\
\x01\0\0\0\x0d\x03\x0e\0\x2e\x74\x65\x78\x74\0\x2e\x72\x65\x6c\x2e\x42\x54\x46\
\x2e\x65\x78\x74\0\x78\x64\x70\x5f\x70\x61\x73\x73\x2e\x5f\x5f\x5f\x5f\x66\x6d\
\x74\0\x78\x64\x70\x5f\x70\x61\x73\x73\0\x2e\x72\x65\x6c\x78\x64\x70\0\x2e\x6c\
\x6c\x76\x6d\x5f\x61\x64\x64\x72\x73\x69\x67\0\x5f\x5f\x6c\x69\x63\x65\x6e\x73\
\x65\0\x2e\x73\x74\x72\x74\x61\x62\0\x2e\x73\x79\x6d\x74\x61\x62\0\x2e\x72\x6f\
\x64\x61\x74\x61\0\x2e\x72\x65\x6c\x2e\x42\x54\x46\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x4e\0\0\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\xc3\x05\0\0\0\0\0\0\x6f\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x40\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\x32\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\x48\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x2e\0\0\0\x09\
\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x10\x05\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\
\x0c\0\0\0\x03\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x5e\0\0\0\x01\0\0\0\
\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x88\0\0\0\0\0\0\0\x12\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x46\0\0\0\x01\0\0\0\x03\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\x9a\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\x6a\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\xa0\0\0\0\0\0\0\0\x1e\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\x66\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x20\x05\0\0\0\
\0\0\0\x20\0\0\0\0\0\0\0\x0c\0\0\0\x07\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\
\0\x0b\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xc0\x03\0\0\0\0\0\0\xbc\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x07\0\0\0\x09\
\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x40\x05\0\0\0\0\0\0\x80\0\0\0\0\0\0\0\
\x0c\0\0\0\x09\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x36\0\0\0\x03\x4c\xff\
\x6f\0\0\0\x80\0\0\0\0\0\0\0\0\0\0\0\0\xc0\x05\0\0\0\0\0\0\x03\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x56\0\0\0\x02\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\x80\x04\0\0\0\0\0\0\x90\0\0\0\0\0\0\0\x01\0\0\0\x04\0\0\
\0\x08\0\0\0\0\0\0\0\x18\0\0\0\0\0\0\0";

	*sz = sizeof(data) - 1;
	return (const void *)data;
}

#ifdef __cplusplus
struct xdp_bpf *xdp_bpf::open(const struct bpf_object_open_opts *opts) { return xdp_bpf__open_opts(opts); }
struct xdp_bpf *xdp_bpf::open_and_load() { return xdp_bpf__open_and_load(); }
int xdp_bpf::load(struct xdp_bpf *skel) { return xdp_bpf__load(skel); }
int xdp_bpf::attach(struct xdp_bpf *skel) { return xdp_bpf__attach(skel); }
void xdp_bpf::detach(struct xdp_bpf *skel) { xdp_bpf__detach(skel); }
void xdp_bpf::destroy(struct xdp_bpf *skel) { xdp_bpf__destroy(skel); }
const void *xdp_bpf::elf_bytes(size_t *sz) { return xdp_bpf__elf_bytes(sz); }
#endif /* __cplusplus */

__attribute__((unused)) static void
xdp_bpf__assert(struct xdp_bpf *s __attribute__((unused)))
{
#ifdef __cplusplus
#define _Static_assert static_assert
#endif
#ifdef __cplusplus
#undef _Static_assert
#endif
}

#endif /* __XDP_BPF_SKEL_H__ */
