TARGET = crash_trace
ARCH = arm64
CROSS_COMPILE = aarch64-linux-gnu-
CC = ${CROSS_COMPILE}gcc
LD = ${CROSS_COMPILE}ld
AR = ${CROSS_COMPILE}ar

BPF_TARGET = ${TARGET:=.bpf}
BPF_C = ${BPF_TARGET:=.c}
BPF_OBJ = ${BPF_TARGET:=.o}

USER_C = ${TARGET:=.c}
USER_SKEL = ${TARGET:=.skel.h}

COMMON_H = ${TARGET:=.h}

all: $(TARGET) $(BPF_OBJ)
.PHONY: all

$(TARGET): $(USER_C) $(USER_SKEL)  $(COMMON_H)
	${CC} -Wall -o $(TARGET) $(USER_C) \
		-I/home/jin/arm64_lib/libbpf/src \
		-I/home/jin/arm64_lib/blazesym/capi/include \
		-L/home/jin/arm64_lib/blazesym/target/aarch64-unknown-linux-gnu/release -l:libblazesym_c.a \
		-L/home/jin/arm64_lib/libbpf/src -l:libbpf.a \
		-L/home/jin/arm64_lib/elfutils-0.191/release/lib -l:libelf.a \
		-L/home/jin/arm64_lib/zlib-1.3.2/release/lib -l:libz.a \
		-lpthread -ldl

$(BPF_OBJ): %.o: $(BPF_C) vmlinux.h  $(COMMON_H)
	clang \
	    -target bpf \
	    -D __BPF_TRACING__ \
        -D __TARGET_ARCH_$(ARCH) \
	    -Wall \
	    -I/home/jin/arm64_lib/libbpf/src \
	    -O2 -g -o $@ -c $<
	llvm-strip -g $@

$(USER_SKEL): $(BPF_OBJ)
	bpftool gen skeleton $< > $@

vmlinux.h:
	bpftool btf dump file /home/jin/arm64_lib/vmlinux format c > vmlinux.h

clean:
	- rm $(BPF_OBJ)
	- rm $(TARGET)

